### ISSUE TITLE
vbb2voc.py: error: the following arguments are required: seq_dir, vbb_dir, output_dir, person_type

### ISSUE THREAD

**Issue by kli017** [CasiaFan/Dataset_to_VOC_converter#18]
hello, I was trying to convert the vbb to voc using vbb2voc.py.  my parameters as below:
python vbb2voc.py --seq_dir=/home/kli/data/pedestrian_data/set00/ \
                  --vbb_dir=/home/kli/data/pedestrian_data/annotations/set00/ \
                  --output_dir=/home/kli/data/pedestrian_data/voc/set00/  \
                  --person_type=person 
but get the error vbb2voc.py: error: the following arguments are required: seq_dir, vbb_dir, output_dir, person_type
Is there any problem with the input format?

**Comment by zongfan2** [comment]
@kli017  I'm not sure about your error. Maybe `\` should be added at end of each line if you run this command in a shell script.
